### ISSUE TITLE
The Latency and Transmit metric  feature request

### ISSUE THREAD

**Issue by davidmkrtchian** [qonto/prometheus-rds-exporter#149]
Before adopting the RDS exporter, I relied on the CloudWatch exporter to gather AWS RDS metrics. However, I noticed that the RDS exporter lacks certain metrics that were available through CloudWatch. Specifically, I found that the following metrics are missing:

- `aws_rds_read_latency_average`
- `aws_rds_write_latency_average`
- `aws_rds_network_receive_throughput_average`
- `aws_rds_network_transmit_throughput_average`

I would greatly appreciate it if these metrics could be incorporated into the RDS exporter. For reference, you can find the definitions of these metrics in the CloudWatch exporter's configuration file at the following location: [CloudWatch Exporter - RDS Metrics](https://github.com/prometheus/cloudwatch_exporter/blob/b15b8ae20b2591a24a0f4b455a96a683ded6fc1b/examples/RDS.yml#L39C1-L62C12).

**Comment by vmercierfr** [comment]
Thanks for raising this feature request.
We don't purposely collect this data, but it's open to discussion.

We try to collect only metrics that are relevant for triggering alerts (part of the [database monitoring framework](https://github.com/qonto/database-monitoring-framework)) or for convenient visualizations in our dashboards (adopting [USE methodology](https://www.brendangregg.com/usemethod.html)).

While network receives/transmit throughput could be relevant to identifying network interface saturation, we haven't seen environments where the network interface could be saturated. Even the smallest RDS instances, like T3/T4 family, have a 5 Gbps interface. Usually, the disk throughput (this metric is collected) is saturated well before the network.

Read/write disk latencies are helpful for deep performance analysis but probably incomplete since you may need enhanced monitoring and some other metrics to be able to identify bottlenecks ([reference](https://repost.aws/knowledge-center/ebs-identify-micro-bursting)).

For these 2 use cases, our recommended approach is to keep the data in AWS CloudWatch and use a performance-oriented dashboard ([example](https://grafana.com/grafana/dashboards/707-aws-rds/)). It avoids Prometheus metrics storage cost, supports metric granularity set on your RDS instance, and allows specialized dashboards.

However, feel free to share alerts, runbooks, or production experiences that you may have with these metrics so we can evaluate if they can fit in this exporter.

**Comment by vmercierfr** [comment]
If you don't mind, I'll close this issue.

As an alternative, you may consider [Cloudwatch exporter](https://github.com/prometheus/cloudwatch_exporter)
