### ISSUE TITLE
description of metrics

### ISSUE THREAD

**Issue by zahornyak** [qonto/prometheus-rds-exporter#32]
please add values for rds_usage_allocated_storage_average and all the rest of the metrics so we can know that there are gigabytes or percent etc.

**Comment by vmercierfr** [comment]
Hello,

Thanks for your message. To make sure I understand correctly, would you like to see examples of README values?

**Comment by vmercierfr** [comment]
I'm sorry for not getting back to you sooner. We merged the changes to rename the metrics. They will be available in 0.4.0, should be released Tomorrow.

At the moment, we don't support AWS RDS Aurora, mainly because we're not Aurora users and don't know anything about it. But it would make sense to support it if the community needs it. Can you open a dedicated question on this subject? If possible, please indicate the key metrics you'd like to see.

**Comment by vmercierfr** [comment]
The [0.4.0](https://github.com/qonto/prometheus-rds-exporter/releases/tag/0.4.0) is now available.

The misleading metrics were renamed:

- From `rds_replication_slot_disk_usage_average` to `rds_replication_slot_disk_usage_bytes`
- From `rds_usage_allocated_storage_average` to `rds_usage_allocated_storage_bytes`

We also updated the Grafana dashboards to reflect these changes, please upgrade them too:

- https://grafana.com/grafana/dashboards/19647-rds-instances
- https://grafana.com/grafana/dashboards/19646-rds-instance-details

Best,
